### ISSUE TITLE
Configureable paths

### ISSUE THREAD

**Issue by fischhase** [Hauer-Heinrich/hh_ckeditor_custom#1]
Dear Heinrich,
thank you for this little configuration ext. I always wonder, why the TYPO3 devs develop features without a build in config (see image cropping, ckeditor ...). So  integrators always need to set up small EXTs for this. It is great of you, to share your ext. 
If you will work on this EXT ever again, I have a small feature request: You create a folder in fileadmin. It would be great to cutomize the paths of CSS and YAML files. So it better fits in different structures. It could be done in the extension manager or via TS (what is possible already.
Thanks and regards
Martin

**Comment by Teisi** [comment]
Hi Martin,

you can customize your CSS, to do that:
1. don't include "Include static TypoScript" from the extension
2. change the path in the .yaml file to your css file
3. add your css in your own typoscript

To change the path to your yaml file - you can now change it in the extension manager -> "gear-wheel" of the extension.

Hope this helps you. :)

**Comment by Teisi** [comment]
Sorry at the moment i cant upload the new version to the "TER" - new TER version and i cant login... :(
So please use the github master version.

**Comment by Teisi** [comment]
@fischhase 
new update today - yesterday's version had a few errors... sry.
