### ISSUE TITLE
TYPO3 v10 compatibilty

### ISSUE THREAD

**Issue by us14v** [Hauer-Heinrich/hh_ckeditor_custom#2]
Hello Heinrich,

are there any plans to release an updated version that's compatible with TYPO3 v10?

Thanks for the extension btw!

**Comment by Teisi** [comment]
yes I can do this :)
It should already be compatible with TYPO3 10.

**Comment by Teisi** [comment]
@us14v can you please confirm that this extension works for you with TYPO3 10?
Thank you :)

**Comment by us14v** [comment]
Sorry for the layte reply!
Yes, it works in v10!
